AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless application infrastructure

Parameters:

  Timeout:
    Type: Number
    Default: "10"

Globals:

  Function:
    Runtime: java8
    MemorySize: 3008
    Timeout: !Ref Timeout
    AutoPublishAlias: live

Resources:

  Lambda1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.symphonia.Lambda1::handler
      CodeUri: lambda1/target/lambda.jar
      Environment:
        Variables:
          TIMEOUT_SECONDS: !Ref Timeout
          PRODUCT_TABLE: !Ref Table1
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get

  Lambda2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.symphonia.Lambda2::handler
      CodeUri: lambda2/target/lambda.jar

  Table1:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: productId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 100
        WriteCapacityUnits: 100
